language: java
jdk: oraclejdk8

services:
  - mysql
  
#cache:
#  directories:
#    - $HOME/.m2
  
before_install:
  - mysql -e 'CREATE DATABASE usersDB;'
  
## Run Integration tests
## script: "mvn verify"
script: "mvn site"

after_success:
  ##- mvn clean test jacoco:report coveralls:report
  ##- mvn site
  - surge --project ./target/site --domain myxxx.surge.sh